version: '3.8'

# ============================================================================
# OpenGristAI - Production Docker Compose
# ============================================================================
#
# Utilise l'image précompilée depuis Docker Hub (nicolassaint/opengristai)
# Idéal pour les utilisateurs finaux qui veulent simplement lancer l'application.
#
# USAGE:
#   1. Créer un fichier .env avec vos variables :
#      OPENAI_API_KEY=sk-...
#      OPENAI_MODEL=gpt-4o-mini
#      GRIST_BASE_URL=https://docs.getgrist.com
#
#   2. Lancer :
#      docker-compose -f docker-compose.prod.yml up -d
#
#   3. Accéder à http://localhost:8000
#
# ============================================================================

services:
  # 🚀 OpenGristAI (Backend + Frontend combinés)
  opengristai:
    image: nicolassaint/opengristai:latest
    container_name: opengristai
    ports:
      - "8000:8000"
    environment:
      # OpenAI Configuration (required)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}

      # LLM Settings (optional)
      LLM_TEMPERATURE: ${LLM_TEMPERATURE:-0.0}
      LLM_MAX_TOKENS: ${LLM_MAX_TOKENS:-}
      LLM_TIMEOUT: ${LLM_TIMEOUT:-60}
      LLM_MAX_RETRIES: ${LLM_MAX_RETRIES:-2}

      # Grist Configuration (optional)
      GRIST_BASE_URL: ${GRIST_BASE_URL:-https://docs.getgrist.com}

      # Agent Settings (optional)
      AGENT_MAX_ITERATIONS: ${AGENT_MAX_ITERATIONS:-15}
      AGENT_VERBOSE: ${AGENT_VERBOSE:-true}

      # Application
      ENVIRONMENT: ${ENVIRONMENT:-production}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

      # CORS Configuration
      # In production, set this to your actual domain(s)
      # Example: https://your-domain.com,https://grist.numerique.gouv.fr
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:8000}

    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
