version: '3.8'

services:
  # 🔧 Backend API (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: opengristai-backend
    ports:
      - "8000:8000"
    environment:
      # OpenAI Configuration (required)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}

      # Grist Configuration (optional - defaults to docs.getgrist.com)
      GRIST_BASE_URL: ${GRIST_BASE_URL:-https://docs.getgrist.com}

      # Application
      ENVIRONMENT: ${ENVIRONMENT:-development}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

  # 🎨 Frontend Widget (SvelteKit)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: opengristai-frontend
    ports:
      - "5173:5173"
    environment:
      # Backend API URL (use 'backend' hostname inside Docker network)
      PUBLIC_CHAT_URL: http://backend:8000/api/v1/chat

      # Development
      NODE_ENV: development
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
    command: npm run dev -- --host 0.0.0.0