version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: grist-ai-postgres
    environment:
      POSTGRES_USER: grist_ai
      POSTGRES_PASSWORD: grist_ai_dev_password
      POSTGRES_DB: grist_ai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grist_ai"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: grist-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grist-ai-api
    ports:
      - "8000:8000"
    environment:
      # Database
      DATABASE_URL: postgresql://grist_ai:grist_ai_dev_password@postgres:5432/grist_ai_db

      # Redis
      REDIS_URL: redis://redis:6379/0

      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Application
      ENVIRONMENT: development
      LOG_LEVEL: DEBUG

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
